create sequence hibernate_sequence start 1 increment 1;

create table article
(
    id int8 generated by default as identity primary key,
    create_timestamp timestamp,
    timestamp timestamp,
    language varchar,
    text text,
    title text,
    wiki varchar
);

create table auxiliary_text
(
    article_entity_id int8 not null,
    auxiliary_text text
);

create table categories
(
    article_id int8 not null,
    category_id int8 not null
);

create table category
(
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name varchar
);